### ISSUE TITLE
Android dependency - different version for compile and runtime classpath

### ISSUE THREAD

**Issue by bardram** [cph-cachet/carp.sensing-flutter#1]
When compiling, we get the error
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:preDebugBuild'.
> Android dependency 'com.android.support:support-compat' has different version for the compile (26.1.0) and runtime (27.1.1) classpath. You should manually set the same version via DependencyResolution
```

**Comment by DARdk** [comment]
Can be found within External Libraries (only Android studio): 
```Flutter Plugins/flutter_blue-x.x.x/android/build.gradle```

**Comment by aneesalahsab** [comment]
plz  how can i fixed this error

FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:preDebugBuild'.
> Android dependency 'com.android.support:support-compat' has different version for the compile (26.1.0) and runtime (27.1.1) classpath. You should manually set the same version via DependencyResolution
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Comment by bardram** [comment]
The same also applies for the `simple_permissions` plugin. Same compile error.

Go into Android Studio and edit the `build.graddle` file for `simple_permissions` to use **SDK 26** (instead of 27).

**Comment by bardram** [comment]
After upgrading to support AndroidX the `compileSdkVersion` should now be 28. So no longer an issue.
