### ISSUE TITLE
Probes not working for iOS devices

### ISSUE THREAD

**Issue by andreaquemada** [cph-cachet/carp.sensing-flutter#11]
There is a file missing in all the probes ending as '-Swift.h', so for example for App Usage the error that comes up is:

` /Users/admin/.pub-cache/hosted/pub.dartlang.org/app_usage-0.0.2/ios/Classes/AppUsagePlugin.m:2:9: fatal error: 'app_usage/app_usage-Swift.h' file not found
    #import <app_usage/app_usage-Swift.h>`

**Comment by thomasnilsson** [comment]
Is this still happening?

For the fix to the specific issue, have a look [here](https://github.com/cph-cachet/carp.sensing-flutter/issues/17).
