### ISSUE TITLE
Context package necessary for background sensing (small enhancement)

### ISSUE THREAD

**Issue by sc00n** [cph-cachet/carp.sensing-flutter#115]
For both iPhone and Android the context package seems to be necessary to do any kind of background sensing. This is kind of stated for Android, but not for iOS. In iOS it only states that you need to use this package if you are interested in location.

I would add a general comment in the beginning such as:

> To keep the app running in the background, the carp_context_package needs to be included. Please follow the instructions [here](https://pub.dev/packages/carp_context_package) on how to use this package.

**Comment by bardram** [comment]
Where are you reading? Where should we add this information?

**Comment by sc00n** [comment]
I meant on the best practices page: https://github.com/cph-cachet/carp.sensing-flutter/wiki/5.-Best-Practice. The information on the context page could be somewhere in the beginning, as it is OS independent. Or it can be in both iOS and Android section.

**Comment by bardram** [comment]
ok - done.
