### ISSUE TITLE
[carp_app_package] MarkedMeasure.lastTime not updated in AppUsageProbe

### ISSUE THREAD

**Issue by koenniem** [cph-cachet/carp.sensing-flutter#150]
At first, it was my understanding that the `history` property of a `MarkedMeasure` determined how far the measure would look back in time. However, I now see that this is only the case if there is not `lastTime` available. In `AppUsageProbe.getDatum()`, `markedMeasure.lastTime` is never updated so it always defaults to 6 hours, no matter the `history` or the last time the probe is run. Or perhaps I'm doing something wrong.

In any case, adding `markedMeasure.lastTime = DateTime.now();` to `AppUsageProbe.getDatum()` seems to give the correct time interval. Only thing is that the usage time of apps is greater than the interval itself. I'm not sure if it's a bug of if that is a restriction put up by Google. Admittedly, the requested interval (10 seconds) is quite small. Consequently, using a `PeriodicTrigger` (`period: Duration(seconds: 10)`, sometimes no app usage can be found.

Follow up question: It seems to give the app usage times of all apps running in the background, not the ones actually being used. Or perhaps that is also related to those restrictions?

**Comment by bardram** [comment]
> At first, it was my understanding that the `history` property of a `MarkedMeasure` determined how far the measure would look back in time. However, I now see that this is only the case if there is not `lastTime` available. In `AppUsageProbe.getDatum()`, `markedMeasure.lastTime` is never updated so it always defaults to 6 hours, no matter the `history` or the last time the probe is run. Or perhaps I'm doing something wrong.
> 
> In any case, adding `markedMeasure.lastTime = DateTime.now();` to `AppUsageProbe.getDatum()` seems to give the correct time interval. 

This is a bug and I've fixed it now.

>Only thing is that the usage time of apps is greater than the interval itself. I'm not sure if it's a bug of if that is a restriction put up by Google. Admittedly, the requested interval (10 seconds) is quite small. Consequently, using a `PeriodicTrigger` (`period: Duration(seconds: 10)`, sometimes no app usage can be found.

This is a too small samplling frequency. Normally, this information is collected on an hourly or daily basis.

> 
> Follow up question: It seems to give the app usage times of all apps running in the background, not the ones actually being used. Or perhaps that is also related to those restrictions?

Yes - this is the case. The API call returns all apps.
