### ISSUE TITLE
Upgrade permission_handler to version 6

### ISSUE THREAD

**Issue by koenniem** [cph-cachet/carp.sensing-flutter#172]
At the moment, all CARP packages depends on `permission_handler ^5.0.0` while the most recent version in 6. This version solves a critical bug in the way API 30 handles permission, see [here](https://github.com/Baseflow/flutter-permission-handler/wiki/Changes-in-6.0.0) and [here](https://github.com/Baseflow/flutter-geolocator/wiki/Breaking-changes-in-7.0.0).

**Comment by bardram** [comment]
I have been looking into this, but this would require that CAMS is upgraded to handle null-safety -- which is on the todo list, but not yet.

**Comment by bardram** [comment]
FYI - I'm working on CAMS null-safety. Will be released soon...

**Comment by bardram** [comment]
CAMS released in null-safe version as version 0.30.x
