### ISSUE TITLE
Missing permissions for Wifi probe

### ISSUE THREAD

**Issue by koenniem** [cph-cachet/carp.sensing-flutter#173]
Per Android API 29, a WiFi scan requires [additional permissions](https://developer.android.com/guide/topics/connectivity/wifi-scan).

I suggest adding the following permissions to the wiki of context_package:
* `<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />`
* `<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />`
* `<uses-permission android:name="android.permission.CHANGE_WIFI_STATE"/>`

**Comment by bardram** [comment]
The Wifi probe / scanning takes place in the `carp_connectivity_package` (and not the context package). 

In the README file of [`carp_connectivity_package`](https://pub.dev/packages/carp_connectivity_package), the above permissions for Android is already stated. 

So - not quite sure where this is missing?
