### ISSUE TITLE
Unhandled Exception: CarpServiceException: 400 Bad Request -  Invalid refresh token:

### ISSUE THREAD

**Issue by DarkToucan** [cph-cachet/carp.sensing-flutter#176]
After running the study and uploading data regularly suddenly the following error starts popping up: 

Trace from Android studio:
E/flutter ( 3796): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: CarpServiceException: 400 Bad Request - Invalid refresh token: fad0d4a8-f5c1-4f09-acf7-be06de658e39
E/flutter ( 3796): #0 CarpService.refresh (package:carp_webservices/carp_service/carp_service.dart:275:5)
E/flutter ( 3796): <asynchronous suspension>
E/flutter ( 3796): #1 CarpService.authenticateWithToken (package:carp_webservices/carp_service/carp_service.dart:186:11)
E/flutter ( 3796): #2 CARPBackend.authenticate (package:dtu_eft/logic/Carp_Backend.dart:119:12)
E/flutter ( 3796): #3 _MainMenuState.initBackend (package:dtu_eft/main.dart:827:16)
E/flutter ( 3796): <asynchronous suspension>
E/flutter ( 3796): #4 _MainMenuState.handleSetup (package:dtu_eft/main.dart:858:7)
E/flutter ( 3796): <asynchronous suspension>
E/flutter ( 3796): #5 _MainMenuState.initState (package:dtu_eft/main.dart:800:5)
E/flutter ( 3796): #6 StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4765:58)
E/flutter ( 3796): #7 ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
E/flutter ( 3796): #8 Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter ( 3796): #9 Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter ( 3796): #10 SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6118:14)
E/flutter ( 3796): #11 Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter ( 3796): #12 Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter ( 3796): #13 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter ( 3796): #14 Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter ( 3796): #15 ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4606:5)
E/flutter ( 3796): #16 ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
E/flutter ( 3796): #17 Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter ( 3796): #18 Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter ( 3796): #19 SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6118:14)
E/flutter ( 3796): #20 Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter ( 3796): #21 Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter ( 3796): #22 SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6118:14)
E/flutter ( 3796): #23 Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter ( 3796): #24 Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter ( 3796): #25 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter ( 3796): #26 StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
E/flutter ( 3796): #27 Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter ( 3796): #28 ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4606:5)
E/flutter ( 3796): #29 StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4791:11)
E/flutter ( 3796): #30 ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
E/flutter ( 3796): #31 Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter ( 3796): #32 Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter ( 3796): #33 SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6118:14)
E/flutter ( 3796): #34 Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter ( 3796): #35 Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter ( 3796): #36 SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6118:14)
E/flutter ( 3796): #37 Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter ( 3796): #38 Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter ( 3796): #39 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter ( 3796): #40 StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
E/flutter ( 3796): #41 Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter ( 3796): #42 ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4606:5)
E/flutter ( 3796): #43 StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4791:11)

**Comment by bardram** [comment]
Should be fixed in v 0.20.1 of `carp_webservices`. Note, however, that this require an upgrade to v 0.20.x of the CAMS API which is a rather large and breaking upgrade....
