### ISSUE TITLE
carp connectivity package needs NSBluetoothAlwaysUsageDescription

### ISSUE THREAD

**Issue by sc00n** [cph-cachet/carp.sensing-flutter#177]
I can only get my app to work if I add NSBluetoothAlwaysUsageDescription key in info.plist

for example:

```
<key>NSBluetoothAlwaysUsageDescription</key>
<string>Bluetooth needed</string>
```

This should be added to readme from 
https://pub.dev/packages/carp_connectivity_package

Thanks,

Merijn

**Comment by bardram** [comment]
Thx. Added this to the upcoming v. 0.30.0 release (null-safe version).
