### ISSUE TITLE
Update dependency uuid 

### ISSUE THREAD

**Issue by jfkominsky** [cph-cachet/carp.sensing-flutter#201]
carp_core relies on an outdated version of uuid, which had breaking changes between versions 2 and 3, but version 3 has null safety. This is creating some incompatibilities in projects that use other packages which have uuid as a dependency (of which there are quite a few).

**Comment by bardram** [comment]
I'm working on a null-safety version of the entire CAMS, including `carp_core` which will be released soon.

**Comment by bardram** [comment]
carp_core null-safe version has been released. The rest of the packages will follow.
