### ISSUE TITLE
RandomTrigger not working 

### ISSUE THREAD

**Issue by luciamontesinos** [cph-cachet/carp.sensing-flutter#202]
@bardram -
RandomTrigger throws an IllegalArgumentException when the startTime and endTime have the same hour (Random.nextInt(0))
https://github.com/cph-cachet/carp.sensing-flutter/blob/5b44dab73d2ab43e0448a4ecbafd40ad0c322d72/carp_mobile_sensing/lib/runtime/trigger_executors.dart#L347-L348

Apart from that, the random dates are generated without any other issue.  However, the task are not being triggered at all.
It seems like the cron job is created correctly. I'm not sure if it has to do with the  sampling duration (currently by default is 2 seconds) or the delay before the task starts
https://github.com/cph-cachet/carp.sensing-flutter/blob/5b44dab73d2ab43e0448a4ecbafd40ad0c322d72/carp_mobile_sensing/lib/runtime/trigger_executors.dart#L407-L416

**Comment by bardram** [comment]
This issue has been addressed in release `0.30.0` which is the null-safe version. Once this is published, you need to use this is the app, and hence upgrade the app to null-safety.
