### ISSUE TITLE
can't build the app because of undefined class

### ISSUE THREAD

**Issue by Kaushalya830** [cph-cachet/carp.sensing-flutter#210]
Undefined class 'CAMSMasterDeviceDeployment'.
Try changing the name to the name of an existing class, or creating a class with the name
![Screenshot_20210901-112253](https://user-images.githubusercontent.com/79890771/132798557-7ba487d4-37ec-437f-8d1e-7b254086a267.png)

**Comment by bardram** [comment]
Can you provide the stack trace, so I can see where this cast fails?

**Comment by bardram** [comment]
`CAMSMasterDeviceDeployment` has been renamed to `SmartphoneDeployment` and this should be fixed in release `0.31.0`
