### ISSUE TITLE
[carp_webservices] AuthenticationDialog uses autocorrect in the username field

### ISSUE THREAD

**Issue by MadsVSChristensen** [cph-cachet/carp.sensing-flutter#213]
The AuthenticationDialog uses autocorrect in the username field, which is an nuisance to users (IMO). 

Suggested change: 
File: carp_webservices/lib/carp_services/authentication_dialog.dart -- Line 31
```dart
TextFormField(
        key: _usernameKey,
        **autocorrect: false,**
        initialValue: username,
        maxLines: 1,
        keyboardType: TextInputType.emailAddress,
        ...
```

**Comment by bardram** [comment]
Agree - fixed and will be released in v. 0.30.1
