### ISSUE TITLE
Error: The getter 'lightSensorStream' isn't defined for the class 'Light'.  - 'Light'

### ISSUE THREAD

**Issue by devhci** [cph-cachet/carp.sensing-flutter#22]
> file:///Users/deku/Documents/development/carp_sensing/carp.sensing-flutter/carp_mobile_sensing/lib/probes/sensors/light_probe.dart:37:41:

 Error: The getter 'lightSensorStream' isn't defined for the class 'Light'.
 - 'Light' is from 'package:light/light.dart' ('file:///Users/deku/Documents/development/flutter/.pub-cache/hosted/pub.dartlang.org/light-0.0.7/lib/light.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'lightSensorStream'.
Stream get lightSensorStream => 

> Light().lightSensorStream;

Seems light Sensorstream no longer exists in 0.0.7

**Comment by bardram** [comment]
The `light` Flutter Plugin has been updated as well as `carp_mobile_sending`.
