### ISSUE TITLE
Long-term triggers on App Tasks

### ISSUE THREAD

**Issue by bardram** [cph-cachet/carp.sensing-flutter#222]
There is a need to support long-term triggers for e.g. adding tasks to the app task queue.

## Scenarios

* recurrent scheduled trigger, like once pr. day or once pr week
* delayed trigger - e.g. after 2 weeks, once or recurrent, specify a delay (duration) 
* timed trigger - specific date (24/12)
* random trigger - N times a day within a time period
* recurrent conditional trigger - check a condition on a regular interval

.. and a combination of such triggers? 

* a delayed recurrent trigger
* recurrent conditional trigger
* timed recurrent trigger - first occurrence 

## Persistence

How to make sure this happens even if the app is not running.....?

**Comment by luciamontesinos** [comment]
Look into this: [WWDC 2020 - Background execution demystified](https://developer.apple.com/videos/play/wwdc2020/10063/?fbclid=IwAR1_oejf0JY9B8yV4d9riMAH4MQsLasO86iVjhwqmAruw2v64_utbuGZIEc)

**Comment by bardram** [comment]
Released with version 0.40.0.
