### ISSUE TITLE
Registered user without active invitations

### ISSUE THREAD

**Issue by luciamontesinos** [cph-cachet/carp.sensing-flutter#228]
If the user is registered but doesn't have any active invitations (the user left a study or the study ended), it should display some kind of information message (e.g "It seems like you are not invited to any ongoing study") and give the option to redirect to sign in.

https://github.com/cph-cachet/carp.sensing-flutter/blob/bf9e34a56506a4ccaa55ef2273ffbacda1243f04/backends/carp_webservices/lib/carp_services/participation_service.dart#L95

**Comment by bardram** [comment]
I don't think showing this kind of message is to be done by the `carp_services` component. It should be up to the app to handle this situation. Each application might want to handle this situation differently. Also - localization (i.e. different languages) would also be handled in the app.
