### ISSUE TITLE
Class 'CarpDataManager' is missing implementations

### ISSUE THREAD

**Issue by bardram** [cph-cachet/carp.sensing-flutter#229]
```
Error: The non-abstract class 'CarpDataManager' is missing implementations for these members:
../…/lib/carp_data_manager.dart:9
     - DataManager.deployment
    Try to either
     - provide an implementation,
     - inherit an implementation from a superclass or mixin,
     - mark the class as abstract, or
     - provide a 'noSuchMethod' implementation.
    class CarpDataManager extends AbstractDataManager {
          ^^^^^^^^^^^^^^^
```

**Comment by bardram** [comment]
I can't recreate this. What version of `carp_mobile_sensing` and `carp_backend` are you using?

**Comment by ossi0004** [comment]
![Screenshot 2021-11-10 at 14 37 59](https://user-images.githubusercontent.com/31033992/141123160-5b54605b-60ac-4f7f-b527-6c81b23cf9b6.png)

All on version 31

**Comment by bardram** [comment]
Can you see what version you're actually using - run a `flutter pub upgrade`? You should be on `carp_backend: ^0.31.2` - see 

 * https://pub.dev/packages/carp_backend
