### ISSUE TITLE
[carp_study_generator] Not up to date with latest version of carp_audio_package: video tasks 

### ISSUE THREAD

**Issue by luciamontesinos** [cph-cachet/carp.sensing-flutter#244]
This line
https://github.com/cph-cachet/carp.sensing-flutter/blob/88c3fa0ec1b07e13a2505035209c0d3b200c755b/utilities/carp_study_generator/lib/cmd/command.dart#L54
needs to be updated to 
```
SamplingPackageRegistry().register(AudioVideoSamplingPackage()); 
```

**Comment by bardram** [comment]
Fixed in version 0.33.0 -- the package is now called `MediaSamplingPackage`
