### ISSUE TITLE
[carp_connectivity_package] Dependency issue

### ISSUE THREAD

**Issue by ademasi** [cph-cachet/carp.sensing-flutter#245]
Due to the lack of support by flutter_blue of rxdart last versions, it created a dependency issue for the sensing packages and in particularly for the connectivity one.

We were able to force rxdart version in the pubspec.yaml without impacting the connectivity package with the following:

`
dependency_overrides:
  rxdart: any 
`

However, a change of dependency to collect Bluetooth information in carp should be investigated. It seems that the development of flutter_blue is stalling.

**Comment by bardram** [comment]
Will be fixed in version 0.33.0
