### ISSUE TITLE
Question: is there an easy way to change the protocol.

### ISSUE THREAD

**Issue by sc00n** [cph-cachet/carp.sensing-flutter#292]
Lets say I want to completely change the protocol in the middle of a study. I have protocolPast and protocolFuture on the phone. What is the easiest way to do this in the app? I want to

1. Stop all sampling from protocolPast
2. initiate protocolFuture
3. Start all sampling from protocolFuture

Just running await Sensing().initialize() again with a new protocol clearly doesn't work. I'm probably ovelrooking something but I couldnt find it. 

I use `DeploymentMode.LOCAL` from in the example app with

```
        _status = await SmartphoneDeploymentService().createStudyDeployment(
          protocolFuture,
          bloc.studyDeploymentId,
        );
```
After this Sensing().initialize() runs normally but doesn't change the protocol.

`controller!.deployment?.hasChanged();`  does not work and `controller!.stop()` gives an error:

```
E/flutter ( 2625): #0      _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:243:24)
E/flutter ( 2625): #1      AbstractExecutor._setState (package:carp_mobile_sensing/runtime/executors/executors.dart:135:27)
E/flutter ( 2625): #2      _AbstractExecutorState.stop (package:carp_mobile_sensing/runtime/executors/executors.dart:298:14)
E/flutter ( 2625): #3      AbstractExecutor.stop (package:carp_mobile_sensing/runtime/executors/executors.dart:168:19)
E/flutter ( 2625): #4      SmartphoneDeploymentController.stop (package:carp_mobile_sensing/runtime/study_controller.dart:342:16)
E/flutter ( 2625): #5      Sensing.initialize (package:flutter_app2/SenseNew/sensing/sensing.dart:65:19)
E/flutter ( 2625): #6      MPathSensingList.doUpdateMobileSensing (package:flutter_app2/KULeuvenSensingFiles/mPathSensingModel.dart:220:21)
E/flutter ( 2625): #7      MPathSensingList.updateMobileSensing (package:flutter_app2/KULeuvenSensingFiles/mPathSensingModel.dart:145:17)
```

**Comment by sc00n** [comment]
Changing the name (deployment id) of study seems to work :

```
_status = await SmartphoneDeploymentService().createStudyDeployment(
  protocol,
  studyName,
);

bloc.studyDeploymentId = studyName;
```

will test it some more

**Comment by bardram** [comment]
There is this option:

```
  // Alternatively mark the deplyment as changed - calling hasChanged()
  // this will force a restart of the entire sampling
  controller.deployment?.hasChanged();
```

This should notify all executors (probes etc.) that the deployment has changed and sampling is to be restarted. But.... as far as I can see, this actually does not work...

**Comment by bardram** [comment]
If this is an entirely **new** protocol (and not an adaptation of the existing one), I would simply create a new deployment like this:

```

    // Stop the old controller
    oldController?.stop();

    // create the new study
    study = await client.addStudyProtocol(protocolFuture);

    // Get a new study controller and try to deploy the study.
    controller = client.getStudyRuntime(study!);
    await controller?.tryDeployment(useCached: false);

    // Configure the new controller.
    await controller?.configure();
```

**Comment by sc00n** [comment]
This worked for me! I also added  
`controller?.start(false);
`
at the end. But I dont know if this is necsessary.

**Comment by bardram** [comment]
> This worked for me! I also added
> `controller?.start(false); `
> at the end. But I dont know if this is necsessary.

Yes - you would need to "stop" the old controller and "start" the new one.
