### ISSUE TITLE
Upgrade issue with 0.5.0 

### ISSUE THREAD

**Issue by devhci** [cph-cachet/carp.sensing-flutter#30]
Because carp_webservices >=0.2.2 depends on carp_mobile_sensing ^0.4.0 and reafel_app depends on carp_mobile_sensing ^0.5.0, carp_webservices >=0.2.2 is forbidden. So, because reafel_app depends on carp_webservices ^0.2.3, version solving failed.

**Comment by bardram** [comment]
New versions of `carp_webservices` and `carp_backend` is now uploaded to pub.dev.
