### ISSUE TITLE
A usertask triggered by another task being completed leaves 4 of the same task in the task queue

### ISSUE THREAD

**Issue by LarsRefsgaard** [cph-cachet/carp.sensing-flutter#318]
https://user-images.githubusercontent.com/1552887/221512885-3fdd6fc4-e835-4c24-a43f-7f50036af7bf.mp4

**Comment by bardram** [comment]
Fixed in [PR #229](https://github.com/cph-cachet/carp_studies_app/pull/229) in the study app.

**Comment by LarsRefsgaard** [comment]
the pr isn't merged so the github issue isn't fixed
