### ISSUE TITLE
_snapshot['createdAt'] returns null 

### ISSUE THREAD

**Issue by devhci** [cph-cachet/carp.sensing-flutter#32]
In  document_reference.dart

 /// The timestamp of creation of this document
  String get createdAt => _snapshot['createdAt'];

Returns Null   bcz 
``
 String get createdAt => _snapshot['createdAt']; ``
 has been changed to  
`` _snapshot['created_at'] `` on  server side

**Comment by bardram** [comment]
Fixed on the backend
