### ISSUE TITLE
accelerometer cannot be summarized in transformer anymore

### ISSUE THREAD

**Issue by sc00n** [cph-cachet/carp.sensing-flutter#336]
In the previous versions (pre 1.0.0), the accelerometer was a multidatum. This was usefull as I could add a transformer that immedieately took the average of all the values (and average of the squared values). Therefore I wouldn't need to safe the countless individual values. 

In the new version the accelerometer (e.g. NON_GRAVITATIONAL_ACCELERATION) does not give a multidatum anymore. Therefore, the previous approach doesn't really work anymore. Is there away to avoid saving all individual values and to save only the average, using a transformer or some other way?

**Comment by bardram** [comment]
```dart
/// A buffer of [Data] objects.
///
/// This type of data is typically collected by the buffering probes, like
/// [BufferingPeriodicProbe] or [BufferingPeriodicStreamProbe].
@JsonSerializable(fieldRename: FieldRename.none, includeIfNull: false)
class DataBuffer extends Data {
  static const dataType = '${CarpDataTypes.CARP_NAMESPACE}.databuffer';

  /// The buffer of data. May be empty.
  List<Data> buffer = [];

  /// The data type of the data in this buffer. Returns null if the [buffer] is
  /// empty.
  String? bufferDataType;
  //  =>
  //     buffer.isNotEmpty ? buffer[0].format.toString() : null;

  @JsonKey(includeFromJson: false, includeToJson: false)
  late DateTime startTime;

  @JsonKey(includeFromJson: false, includeToJson: false)
  DateTime? endTime;

  DataBuffer() {
    startTime = DateTime.now();
  }

  void add(Data value) => buffer.add(value);

  void close() {
    endTime = DateTime.now();
    bufferDataType = buffer[0].format.toString();
  }

  @override
  Function get fromJsonFunction => _$DataBufferFromJson;
  factory DataBuffer.fromJson(Map<String, dynamic> json) =>
      FromJsonFactory().fromJson(json) as DataBuffer;
  @override
  Map<String, dynamic> toJson() => _$DataBufferToJson(this);
}
```

**Comment by bardram** [comment]
```dart
class BufferingPeriodicStreamProbeImpl extends BufferingPeriodicStreamProbe {
  DataBuffer buffer = DataBuffer();

  @override
  Stream<dynamic> bufferingStream;

  BufferingPeriodicStreamProbeImpl(this.bufferingStream) {
    debug('$runtimeType - created');
  }

  @override
  void onSamplingData(event) {
    if (event is Measurement) {
      buffer.add(event.data);
    }
  }

  @override
  void onSamplingStart() {
    debug('$runtimeType - onSamplingStart()');
    buffer = DataBuffer();
  }

  @override
  void onSamplingEnd() {
    debug('$runtimeType - onSamplingEnd()');
    buffer.close();
  }

  @override
  Future<Measurement?> getMeasurement() async =>
      Measurement.fromData(buffer, buffer.startTime.microsecondsSinceEpoch)
        ..sensorEndTime = buffer.endTime?.microsecondsSinceEpoch;
}
```

**Comment by bardram** [comment]
Update to `sensor_package.dart`

```dart
  static const String BUFFERING_ACCELERATION =
      '${CarpDataTypes.CARP_NAMESPACE}.bufferingacceleration';

...

        DataTypeSamplingScheme(
          DataTypeMetaData(
            type: BUFFERING_ACCELERATION,
            displayName: "Buffering Accelerometer",
            timeType: DataTimeType.TIME_SPAN,
          ),
        ),

...

      case BUFFERING_ACCELERATION:
        return BufferingPeriodicStreamProbeImpl(
            UserAccelerometerProbe().stream);

```

**Comment by bardram** [comment]
Now I have been thinking (and even implemented a prototype for buffering of data -- see #338).

But I've come to the conclusion that introducing a buffer of data (similar to the old `MultiDatum`) is the wrong approach. 

Instead, we need to define a new `Measure` which defines what we want to measure. And then provide a probe for doing this.  This is similar to the `LightProbe` which is a `BufferingPeriodicStreamProbe` that buffers light data and returns metadata on light (incl. max lux and average lux). 


This measure and its probe should be part of a sampling package.  You can either [create your own sampling package](https://github.com/cph-cachet/carp.sensing-flutter/wiki/5.-Extending-CARP-Mobile-Sensing#Adding-New-Sampling-Capabilities) or you can provide me with the code and I can add is as part of the `sensor` sampling package?

**Comment by sc00n** [comment]
I created some (actually 4, I wasn't able to figure out how to combine everything for the non master branch) pull requests for a new sensor, the NON_GRAVITATIONAL_ACCELERATION_AVERAGE:

- https://github.com/cph-cachet/carp.sensing-flutter/pull/343
- https://github.com/cph-cachet/carp.sensing-flutter/pull/342
- https://github.com/cph-cachet/carp.sensing-flutter/pull/341
- https://github.com/cph-cachet/carp.sensing-flutter/pull/340

In general it works just like the Ambient Light sensor, where the accelerometer is averaged over a period of time. I summarized it in 7 variables: 

```
    // xm, ym, zm: normal averages (or means)
    // xms, yms, zms: averages of squared values
    // n: number of values included
  double? xm; 
  double? ym;
  double? zm;
  double? xms;
  double? yms;
  double? zms;
  int? n;
```

using the normal average and average of squared value, the standard deviation can also be computed later:
![image](https://github.com/cph-cachet/carp.sensing-flutter/assets/48179232/854e117d-981c-4388-929e-36a0420e047e)
