### ISSUE TITLE
apps/carp_mobile_sensing_app buid and run problem with dart 3 and flutter 3.13.x

### ISSUE THREAD

**Issue by mobile-dev-kh** [cph-cachet/carp.sensing-flutter#348]
We have a lot of problems trying to implement and run this example. Please update the content so that we can see a good example and provide suggestions for using your applications.
We have tried a lot to deal with it but to no avail.
I hope to use the libraries with their latest versions in the example. Thank you

**Comment by LarsRefsgaard** [comment]
Have you tried it on branch `develop-1.1.0`?

**Comment by mobile-dev-kh** [comment]
@LarsRefsgaard yes i tried on branch develop-1.1.0 , i get this error with Bluetooth :Launching lib\main.dart on AOSP on IA Emulator in debug mode...
√  Built build\app\outputs\flutter-apk\app-debug.apk.
D/flutter/CALL_LOG(13874): onAttachedToEngine
D/flutter/CALL_LOG(13874): init. Messanger:io.flutter.embedding.engine.dart.DartExecutor@6dd1349 Context:android.app.Application@b77a44e
D/flutter/CALL_LOG(13874): onAttachedToActivity
D/FlutterLocationService(13874): Creating service.
D/FlutterLocationService(13874): Binding to location service.
D/eglCodecCommon(13874): setVertexArrayObject: set vao to 0 (0) 1 0
D/EGL_emulation(13874): eglMakeCurrent: 0xe07a8b00: ver 2 0 (tinfo 0xc8debdc0)
I/OpenGLRenderer(13874): Davey! duration=734ms; Flags=0, IntendedVsync=27640488040206, Vsync=27640488040206, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=27640490930300, AnimationStart=27640491020100, PerformTraversalsStart=27640491074500, DrawStart=27640501948600, SyncQueued=27640505905900, SyncStart=27640515656700, IssueDrawCommandsStart=27640517020500, SwapBuffers=27641135011700, FrameCompleted=27641232107000, DequeueBufferDuration=46144000, QueueBufferDuration=12291000,
D/permissions_handler(13874): No android specific permissions needed for: 19
D/permissions_handler(13874): No android specific permissions needed for: 19
I/flutter (13874): ===========================================================
I/flutter (13874):   CARP Mobile Sensing (CAMS) - SmartPhoneClientManager
I/flutter (13874): ===========================================================
I/flutter (13874):              device : PSR1.180720.122 - AOSP on IA Emulator GOOGLE [SDK 28]
I/flutter (13874):  deployment service : SmartphoneDeploymentService
I/flutter (13874):   device controller : DeviceController [6]
I/flutter (13874):   available devices : (Smartphone, LocationService, AirQualityService, ..., PolarDevice, ESenseDevice)
I/flutter (13874):         persistence : carp.db
I/flutter (13874): ===========================================================
I/flutter (13874): SmartphoneDeploymentController - Study deployment '3db56440-7616-11ee-9c4b-29f01bd82c83' successfully deployed.
D/FlutterLocationService(13874): Start service in foreground mode.
E/MethodChannel#polar(13874): Failed to handle method call
E/MethodChannel#polar(13874): kotlin.UninitializedPropertyAccessException: lateinit property api has not been initialized
E/MethodChannel#polar(13874): 	at dev.rexios.polar.PolarPlugin.onMethodCall(PolarPlugin.kt:104)
E/MethodChannel#polar(13874): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/MethodChannel#polar(13874): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#polar(13874): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/MethodChannel#polar(13874): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#polar(13874): 	at android.os.Handler.handleCallback(Handler.java:873)
E/MethodChannel#polar(13874): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#polar(13874): 	at android.os.Looper.loop(Looper.java:193)
E/MethodChannel#polar(13874): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/MethodChannel#polar(13874): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#polar(13874): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MethodChannel#polar(13874): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/flutter (13874): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, lateinit property api has not been initialized, null, kotlin.UninitializedPropertyAccessException: lateinit property api has not been initialized
E/flutter (13874): 	at dev.rexios.polar.PolarPlugin.onMethodCall(PolarPlugin.kt:104)
E/flutter (13874): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/flutter (13874): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/flutter (13874): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/flutter (13874): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/flutter (13874): 	at android.os.Handler.handleCallback(Handler.java:873)
E/flutter (13874): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter (13874): 	at android.os.Looper.loop(Looper.java:193)
E/flutter (13874): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/flutter (13874): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (13874): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/flutter (13874): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/flutter (13874): )
E/flutter (13874): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
E/flutter (13874): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
E/flutter (13874): <asynchronous suspension>
E/flutter (13874):
E/AndroidRuntime(13874): FATAL EXCEPTION: Thread-4
E/AndroidRuntime(13874): Process: dk.cachet.carp_mobile_sensing_app, PID: 13874
E/AndroidRuntime(13874): java.lang.NullPointerException: Attempt to invoke virtual method 'android.bluetooth.le.BluetoothLeScanner android.bluetooth.BluetoothAdapter.getBluetoothLeScanner()' on a null object reference
E/AndroidRuntime(13874): 	at io.esense.esenselib.ESenseScanner.<init>(ESenseScanner.java:30)
E/AndroidRuntime(13874): 	at io.esense.esenselib.ESenseManager$1.run(ESenseManager.java:408)
E/AndroidRuntime(13874): 	at java.lang.Thread.run(Thread.java:764)
I/Process (13874): Sending signal. PID: 13874 SIG: 9
Lost connection to device.

Exited.

**Comment by bardram** [comment]
All the packages have now been released in version 1.4.0.  This includes updating the demo app and update all the documentation on the wiki. 

I hope this all works now. 

Note that the default branch is renamed to `main`.
