### ISSUE TITLE
Weather data always at Copenhagen location

### ISSUE THREAD

**Issue by sc00n** [cph-cachet/carp.sensing-flutter#349]
Weather data (ContextSamplingPackage.WEATHER) is always collected on the following location on iOS:

I/flutter (24464):   "latitude": 55.7944,
I/flutter (24464):   "longitude": 12.4463,

This is because in location_manager.dart _lastKnownLocation is initialized as

`Location _lastKnownLocation = Location(latitude: 55.7944, longitude: 12.4463);`

In Android, where I use _ContextSamplingPackage.CURRENT_LOCATION_ the location gets adapted after a while. On iOS, where I use ContextSamplingPackage.LOCATION, it does not adapt and the weather report is always on Copenhagen.

- If there is no real location, the weather report should give nothing
- _lastKnownLocation should also work with ContextSamplingPackage.LOCATION or even without location package

**Comment by bardram** [comment]
Fixed and published in carp_context_package version: 1.3.2.

I've removed the "last known location" and the probes are always trying to get the current location when asking for weather and air data.
