### ISSUE TITLE
Too many location updates

### ISSUE THREAD

**Issue by bardram** [cph-cachet/carp.sensing-flutter#37]
The location probe returns a lot of location events -- up to 10-15 pr. minute. This is too much and should be reduced.

**Comment by thomasnilsson** [comment]
This can be solved by implementing a DatumProbe for Location, which uses getLocation from the `location` package

**Comment by bardram** [comment]
The `location` measure has now been changed to a `PeriodicMeasure` with a sampling frequency and accuracy. The default setting is

```
LocationMeasure(MeasureType(NameSpace.CARP, LOCATION), name: 'Location', enabled: true, frequency: 10 * 1000, accuracy: LocationAccuracy.BALANCED)
```

**Comment by bardram** [comment]
Closed with the above additions.
