### ISSUE TITLE
403 error when trying to access a newly created resource

### ISSUE THREAD

**Issue by SlimShadyIAm** [cph-cachet/carp.sensing-flutter#392]
## Problem

When you are invited to a new study and you are already signed in, and you try to accept the invitation, you will get a 403 error. This is because your token does not have the claims required to access the newly created resource.

Furthermore, when the deployment is null because the backend throws an error such as in this case, an assertion will fail in the research package. This should be handled differently - we should throw an error so the app can handle this error.

## Solution

Whenever you get a 403 error, try to refresh the token manually and re-try the request. If it fails again, you really are not supposed to be able to access that request and you should somehow handle that (on the portal we redirect to the homepage and show an error snackbar that you don't have access).

**Comment by bardram** [comment]
<img width="944" alt="image" src="https://github.com/cph-cachet/carp.sensing-flutter/assets/1196642/f25a7fa1-ebfb-4e1d-9ef1-422afd33eb56">
