### ISSUE TITLE
Webservices: JSON serialization for OAuthToken class

### ISSUE THREAD

**Issue by barnabashomola** [cph-cachet/carp.sensing-flutter#58]
Right now the `OAuthToken` class does not support a `toJson` function making it possible to serialize. The only available function is `toString` but that has a less clear structure.

JSON serialization would be useful for for e.g. storing the token in shared preferences as a string for later usage.

**Comment by bardram** [comment]
Has been implemented and released as part of version `0.4.1`:

* https://pub.dev/packages/carp_webservices#-changelog-tab-

Hope it is what is needed.
