### ISSUE TITLE
Webservices: create consent document is deprecated with new CARP version

### ISSUE THREAD

**Issue by barnabashomola** [cph-cachet/carp.sensing-flutter#67]
I can't create a new consent document in Carp with `createConsentDocument` anymore. 

As far as I can see that is because the call now should be 
`POST {{PROTOCOL}}://{{SERVER_HOST}}:{{SERVER_PORT}}/api/deployments/{{DEPLOYMENT_ID}}/consent-documents` 
and instead the version now uses 
`POST {{PROTOCOL}}://{{SERVER_HOST}}:{{SERVER_PORT}}/api/studies/{{DEPLOYMENT_ID}}/consent-documents`
so `studies` instead of `deployments`.

**Comment by bardram** [comment]
Should be fixed with release version 0.4.4
