### ISSUE TITLE
CARP webservices: CarpServiceException toString() cannot handle null message throws String error

### ISSUE THREAD

**Issue by MadsVSChristensen** [cph-cachet/carp.sensing-flutter#72]
Error:

```
E/flutter ( 7795): [ERROR:flutter/shell/common/shell.cc(209)] Dart Error: Unhandled exception:
E/flutter ( 7795): Invalid argument(s)
E/flutter ( 7795): #0      _StringBase.+  (dart:core-patch/string_patch.dart:267:57)
E/flutter ( 7795): #1      CarpServiceException.toString 
```

Description: 
If the response from a HTTP request returns an error and Carp Webservices creates a `CarpServiceException`, the message can be null (or might not have been added correctly in Carp Webservices). This results in an error when the Exception is later printed using the `toString()`, as it is not checked/handled.

Error code:   - CarpService.dart line 498.
```
  String toString() => "CarpServiceException: " + ((httpStatus != null) ? "$httpStatus - " : "") + message;
```

Proposed solution:
```
String toString() => "CarpServiceException: ${(httpStatus != null) ? httpStatus + " - " : ""} ${message ?? ""}";
```

**Comment by bardram** [comment]
Released in `0.4.5+5`
