### ISSUE TITLE
webservices - id is null even if there's a document in setData

### ISSUE THREAD

**Issue by barnabashomola** [cph-cachet/carp.sensing-flutter#89]
In [setData](https://pub.dev/documentation/carp_webservices/latest/carp_services/DocumentReference/setData.html) there's a check if id==null in order to call the update method instead. According to my experience the id is null even if there's a document with the same name.

**Comment by bardram** [comment]
I need some more information on this. How do you get an existing document with and id that is null even though the document exist? Normally, if the id is null, the document does not exist. If the document exist, you should use the `get()` method to get it (including its id).
