### ISSUE TITLE
Build error in example app

### ISSUE THREAD

**Issue by JacobAagaard** [cph-cachet/carp.sensing-flutter#94]
Steps to reproduce:

1. Clone carp.sensing-flutter repo
2. `cd carp_mobile_sensing_app`
3. `flutter run`

This produces the following error:
```
pub.dartlang.org/carp_audio_package-0.9.0/lib/audio_datum.dart:26:14: 
Error: Too many positional arguments: 0 allowed, but 1 found.
Try removing the extra positional arguments.
      : super(filename);
             ^
FAILURE: Build failed with an exception.
```

I tried removing the `filename` argument locally which seemed to resolve the issue, allowing me to build and run a development version of the app as expected.

**Comment by bardram** [comment]
It should be:

`: super(filename: filename);`

Has been fixed in version `0.9.3`.
